title : Dano Williams is a website and a designer.

author :
  name : Dano Williams
  email : dan.o.williams@gmail.com
  github : thisisdano
  twitter : thisisdano

exclude: [node_modules, package.json, npm-debug.log, Gruntfile.js, styles/scss]